import { loadLibraryFromBlob } from "@excalidraw/excalidraw/data/blob";

import type {
  ExcalidrawImperativeAPI,
  LibraryItems,
} from "@excalidraw/excalidraw/types";

/**
 * voxen: the "BTAB dashboard kit" — an Excalidraw library of btab
 * vendor-dashboard parts (shell, cards, tables, …) that every visitor gets in
 * the Library panel by default.
 *
 * The kit is a static file in `public/` (generated by `scripts/btab-kit/`).
 * Kit items own the `btab-kit:` id prefix: on every load all items with that
 * prefix are replaced by the file's items, and every other item (the user's
 * own library) is left untouched. Regenerating the kit therefore updates it
 * for everyone without wiping anyone's library.
 */
export const BTAB_KIT_ID_PREFIX = "btab-kit:";
export const BTAB_KIT_URL = `${
  import.meta.env.BASE_URL
}btab-dashboard.excalidrawlib`;

export const isBtabKitItem = (item: { id: string }) =>
  item.id.startsWith(BTAB_KIT_ID_PREFIX);

/** user items first (keeps their order), kit items after */
export const mergeBtabKit = (
  currentItems: LibraryItems,
  kitItems: LibraryItems,
): LibraryItems => [
  ...currentItems.filter((item) => !isBtabKitItem(item)),
  ...kitItems.filter(isBtabKitItem),
];

export const installBtabKit = async (
  excalidrawAPI: ExcalidrawImperativeAPI,
) => {
  let kitItems: LibraryItems;
  try {
    // `no-cache`: revalidate so a regenerated kit shows up on the next load
    const res = await fetch(BTAB_KIT_URL, { cache: "no-cache" });
    if (!res.ok) {
      throw new Error(`HTTP ${res.status}`);
    }
    kitItems = await loadLibraryFromBlob(await res.blob(), "published");
  } catch (error: any) {
    console.warn(`BTAB kit not loaded: ${error.message}`);
    return;
  }
  // a function source runs after every queued library update (incl. the
  // initial IndexedDB load), so we always merge into the user's real library
  await excalidrawAPI.updateLibrary({
    libraryItems: (currentItems) => mergeBtabKit(currentItems, kitItems),
  });
};
